workflows:
  ios-cache-pod-workflow:
    name: iOS Cache Workflow (With Pods)
    environment:
      xcode: latest # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      cocoapods: default
      distribution_type: ad_hoc # app_store| ad_hoc | development | enterprise
      bundle_identifier: br.com.callcab.user.tax
      vars:
        BUNDLE_ID: "br.com.callcab.user.tax"
        XCODE_WORKSPACE: "NewTaxi.xcworkspace"
        XCODE_SCHEME: "NewTaxi"
        XCODE_PROJECT: "NewTaxi.xcodeproj"
        APP_STORE_APPLE_ID: 6474373220
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - name: Install coccoapods plugins
        script: |
          gem install cocoapods-xcremotecache
          pod install
      - name: Increment build number
        script: |
          #!/bin/sh
          set -e
          set -x
          agvtool new-version -all $(($BUILD_NUMBER + 1))
      #- name: Build ipa for development
       # script: |
       #   xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
artifacts:
  - build/ios/ipa/*.ipa
  - /tmp/xcodebuild_logs/*.log
  - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
  - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
