# Este arquivo define a configuração do seu projeto Codemagic
# Para mais informações, consulte https://docs.codemagic.io/yaml/

app_id: "br.com.callcab.user.tax"
app_version: 1.0.0
app_name: "CallCab"

# Configurações do projeto

workflows:
  ios-cache-pod-workflow:
    environment:
      xcode:  14 # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      cocoapods: default
  # Este fluxo de trabalho é executado quando você envia seu código para o Codemagic
  build:
    # Configurações de assinatura
    signing:
      # Escolha "Sem assinatura" para gerar um .ipa sem assinatura
      method: "none"
    # Configurações do App Store Connect
    app_store_connect:
      # Desmarque esta opção para não enviar o .ipa para o App Store Connect
      distribute: false
